version: '3.8'

services:
  redis:
    build:
      context: requirements/bonus/redis
    networks:
      - main_net
    hostname: redis
    restart: unless-stopped
  adminer:
    build:
      context: requirements/bonus/adminer
    networks:
      - main_net
    hostname: adminer
    restart: unless-stopped

networks:
  main_net:
