version: '3.8'

services:
  mariadb:
    build:
      context: requirements/mariadb
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - main_net
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - main_net
    volumes:
      - wordpress_data:/var/www/html:ro
    restart: unless-stopped
    hostname: nginx

  wordpress:
    build:
      context: requirements/wordpress
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mariadb
    networks:
      - main_net
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    hostname: wordpress

networks:
  main_net:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/mariadb'
