version: '3.7'

services:
  #mariadb:
  #build: requirements/mariadb
  #ports:
  #- 3306:3306
  #networks:
  #- main_net
  nginx:
    build: requirements/nginx
    ports:
      - 80:80
    networks:
      - main_net

networks:
  main_net:
