version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - main_net
    hostname: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
    networks:
      - main_net
    volumes:
      - wordpress_data:/var/www/html:ro
    hostname: nginx

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - main_net
    volumes:
      - wordpress_data:/var/www/html
    hostname: wordpress

networks:
  main_net:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/mariadb'
