version: '3.8'

services:
  redis:
    build:
      context: requirements/bonus/redis
    networks:
      - main_net
    hostname: redis
    restart: unless-stopped
  adminer:
    build:
      context: requirements/bonus/adminer
    networks:
      - main_net
    hostname: adminer
    restart: unless-stopped
  ftp:
    build:
      context: requirements/bonus/ftp
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    networks:
      - main_net
    hostname: ftp
    restart: unless-stopped
    volumes:
      - wordpress_data:/data
  webpage:
    build:
      context: requirements/bonus/webpage
    networks:
      - main_net
    hostname: webpage
    ports:
      - '8080:80/tcp'
    restart: unless-stopped
